'''
Given a string, s, containing an RNA sequence, return the protein
encoded by string s.

Approach:
First create dictionaries for each codon sequence.
Then need to parse RNA string in groups of 3 nucleotides.
To do so, will have to split RNA string by index and append each element
to a list. 
Then, iterate through list, matching each element to the dictionary,
and appending the result into a new list, protein_string. 
Append protein_string until the stop codon is met

Pseudocode:
# Define codon dictionary first
rna_protein_dictionary = {spam: eggs} # spam = RNA codon, eggs = peptide
# Create codon list from rna_string and convert codon to peptide chain
define function (rna_string):
    rna_codons = []
    peptide_chain = []
    index_to_split = 3
    for index in range 0:length(rna_string), in increments of index_to_split:
        append rna_string[index to index + index_to_split] to rna_codons
    
    # Convert codon to peptide
    for codon in rna_codon:
        append rna_protein_dictionary[codon] to peptide_chain
        if peptide_chain[-1] == "Stop":
            break
    
    return peptide_chain
'''

rna_protein_dictionary = {
    "UUU": "F",
    "CUU": "L",
    "AUU": "I",
    "GUU": "V",
    "UUC": "F",
    "CUC": "L",
    "AUC": "I",
    "GUC": "V",
    "UUA": "L",
    "CUA": "L",
    "AUA": "I",
    "GUA": "V",
    "UUG": "L",
    "CUG": "L",
    "AUG": "M",
    "GUG": "V",
    "UCU": "S",
    "CCU": "P",
    "ACU": "T",
    "GCU": "A",
    "UCC": "S",
    "CCC": "P",
    "ACC": "T",
    "GCC": "A",
    "UCA": "S",
    "CCA": "P",
    "ACA": "T",
    "GCA": "A",
    "UCG": "S",
    "CCG": "P",
    "ACG": "T",
    "GCG": "A",
    "UAU": "Y",
    "CAU": "H",
    "AAU": "N",
    "GAU": "D",
    "UAC": "Y",
    "CAC": "H",
    "AAC": "N",
    "GAC": "D",
    "UAA": "Stop",
    "CAA": "Q",
    "AAA": "K",
    "GAA": "E",
    "UAG": "Stop",
    "CAG": "Q",
    "AAG": "K",
    "GAG": "E",
    "UGU": "C",
    "CGU": "R",
    "AGU": "S",
    "GGU": "G",
    "UGC": "C",
    "CGC": "R",
    "AGC": "S",
    "GGC": "G",
    "UGA": "Stop",
    "CGA": "R",
    "AGA": "R",
    "GGA": "G",
    "UGG": "W",
    "CGG": "R",
    "AGG": "R",
    "GGG": "G" 
}

def translate_rna_to_peptide_chain(rna_string):
    rna_codons = []
    peptide_chain = []
    index_to_split = 3
    # Create a list of codons
    for index in range(0, len(rna_string), index_to_split):
        rna_codons.append(rna_string[index:index + index_to_split])
    
    # Convert codon to peptide
    for codon in rna_codons:
        if rna_protein_dictionary[codon] != "Stop":
            peptide_chain.append(rna_protein_dictionary[codon])
        else:
            break
    
    result = "".join(peptide_chain)
    
    return print(result)

translate_rna_to_peptide_chain("AUGGAUGUGGGGUGGUGUUGUGUACGACUUUUGCCGAGUGCCCUACGCUCUAGCGUAGUCUGCUCCACGGGUUUGAUCCUGCCGCAUUCCCGGUACUGUGCCCUCCCACCAUACUCGCGUCGAGCUCUGGCCUUCCUCACACAUAACACAGAUAGUGCCUGUAUAUCAAAGCAACCGUUAUCAGAUCCAGUGCGUUCCACAUCACGAGCCGUCUGGUGGUUGGCGCAUUCGCAAAACGAGAAUUCCUGCAGUGAAAUUGGCACGUUGCCUGCUAAGUGUACACCGAAGCGUCAAGUUAAUGAAUUGUCCACCUGUCGAAUAACUGAGUGUGAACAGGCGGGUCCCCUGUUGUCACGGUAUAGCACUAUCCGACCUACAGAGACGGAGAUGGGUAUUGGGCCGAAAUACAUACUAACUGAACCACGCACCCGUCUCAUCCCAAUGACUGGCAGUUGUGUCCAUGACAGGCACGAGGGCCUACGAGCAGAACUCUCCCUGUUCCGAGCGCGCGACGACCUAAGGUGGACUGAAACGUGGCCUUCAUGGCCUCCUGGUUCUGCUGCGCCGAAUGAUUUUGAUCGGUCGAGGGGCUCAUUGAAGCAGCUGCUGCCGCCCCUAACUGAGGAUUGUUCCGGGCGCGAUUCCAAGGUUCUCGCGAUGUGUGCCCGACCUUCAGGUGACACCCAUUUGCGGCUGAGUAAAAACACCGGAGACUCGUCAGGGUUAAUAGCACCGAUCAUAAAGACCGGUGCUAUGGCCGGUUCGCCCACUUACCGCCGGCUAGCGAACAGGGGAGCGUUACAGGUGGAAUACUACGAACUGACGCAUGGGUCCCCAGCACUUAUUCGUCUAAGGGUGCAGGCUUAUCUGACCUGGAAUUAUGGGGAGAUGCUUCGGUCAAAAGAGAGACCUCUCGCAGGUUUGGUGCCCACCACUCCGCCGGUAUACGCUCACAUGGGCGACCCGCGGCGCACCCUGUUAACAGAUUUGAAUGUAUAUUUUGACUUUGUUAAAGGGGGCCACGUAAAAUCCGUUCGCGGUUUUCCUUCUUCCAUGAUUUGUGAUCCUCAGCUUACCAUCUGGUCGGUCAUAAGUCUUAUAUGGACACUCAUGAUGGUGGGGGCAUUGGUUUGCAUAAUCGACUUCGGGUGGCCGUGCGAUGUGCCAGAUUUAAUUUGGGGGUUAACACGCAUACGUAAGUGGAGGUCCCUUGGAGACAAAUUGACUGGCGCUGCGCAACUAAGGCUAUCAGGUCAUGGGCUUGCAAUAUCAGAUGUCUUUAGGGUAUCACUACAAAGACUAAGUGCAGAAUGUAUACUCGUGACCGACGCUGCUGACCUUAUGGAGCGGUUCGCUUACAUUUAUCAACUUUGGACUUUACGCACGCAUCCACAAGUCGUGAUCAAAAUUUCCGCCACGCGAAUAUUACGUCGGCUGCCCUAUUGGUGCAGUAGGUUGUUUCUUCCGUGUUACAGUCUUAGGGUAGCUAUUGAUAAUAGGUUACAAAAGCAUCAAUUGGCCACCAUCAGGCUGCUCUCCAGUCUAGAGCUUUCGUCGUCCAGCCACACCCGAGCGUCCUCCAGGCGUAACGCCCCUAUACGACUGAACUCACCGAUGCCUUUGUCAAUGUACAUUCGAUCUCUUGUGCUCAAAAUGAAGGUACCCCCCAUUGCAGGGGCCAUCCCGGCAGGGCCUUCUUCACGUGCGAUCGUAAUACACACCUAUACCGGGCCUCGUUAUUCCGGAAUCCACUUACCAAACUAUGGUGGCGUAAAGUAUCAACGAUGCCCUCGAGUCAAUACUCCCAUGCGGCAUACGCAAUCUAGAUAUGCUCGUGACUUGGCGGCGUCCCGGGUUACGCAAGGAACCCAUCGGAUAUUUGAGUACGAAGCUUGUGAUAUUAUAUUCUAUAUGACGAACUAUAAUUGCCGCAUGCCUUUCCGAACAGUCGUGUACGGCUUACCUAGGAACCAACAGAUAAUGUAUAGGAUAAACUCACCGGGAUUUCGCAGUGACUUUCCAGUAAACGAACAUUGCAGUUGCCCCAAACAAUUGACCUCAGGACUACCAAUUUCUCAGCCGCUCACCGCUUUUACUGUAACACACGCAGACCGACAUUCAGGGAAGCGAUCUAAGUUAGUGAGUCACUUACGUCGUGGAACAUCGAAUGUAGUCACCCAUAUGGCGCCUAUAACGAGCCAACUCAUAUUCACAACUACAGCUCCGGCAGGACAGGGCACGUGGGCACGUAUUUUGCUCGUCAACCCAAUAUUCGAACGAUAUCUGCUGUUCCUGGACCUCAAAUGUUAUUCUAGUCUGAGUAGGAUGACGAACAAGUGCAUUGGCCGUGAGCGAUACUCCUUCGUGAGCGCGUCGACGCAGUUACGGAAUCCGUCUCGCCUCGUUCGGCAAUUCCGCGCUGACAUUAAGUACAUGAUAAGUCGGCUUUCUGAAUCCCGGUGUGUCGGUGGCCUGGCCGAUCGCAUUUUCAAUUUUGGUCAGCAAAAGGAUUUUCAGCCCUCGGCUGCGUUGCUAGAUUGGUCCCAAUUAGGUAGACUAGGGCUCCACUGCCAGGGGGGUCCCGCCCCCGUUAACGGACUAUACGUUCCGGGUUGCGGAAAGUUUCGCAACGCGUGCGCAGUCGCCCGUAGUUGCUGUGUUCGGUCGGGCAGGGUCCAAGACCCCUUGUCUAUGAAACUCUCAGGAGGAUGGGUCGAAGUGGGAAAGACCCAACAACCUGGCGAGUGUGGCCGAACAGCUGCGCUUCGCACGACAACGCAAGCUUCCAUCGUUCAACAUAAGAAGAGAAGUAGGAAAACCCUCUUGGGCUACGCAGUUACAGCGAAUAACAGAAAUUUCAACUCGCGACGAGAAGCAGGAAAAGUAAGAGUGACCCUCGAUUCAAUACGGGCGCGGAUUCUCUCUAUGAAGCCAUCCAUCCUUAGAGCCGUCCCGGAUCGUAAAGAGCGCCCGAAUACUCCCUGUGUAUUAGCAUUACGUCUCCAAACAGAUAAUAGAGAAAGCCAAUCCAUUUGUGCGUUUAUCACGUCCAAAGGCUCCCGACUAAUACCUCUUCGCACCCACGAUCAACAACAGUCAAUGAGCGGAGUCGGUUGUUGUAGAGAUCGAUGCGAUGCAUGGAGAAACCGUAGGUUACCUUCGGCUUUGCGGCCAGCUCCUGCUCUAGUGGUAUCCAUCCUCGACAAGGACAUAGGACAUGCAUCGUUGUUGAGUCUAACACCUUUUGUCUACACUGCGCAAUAUCACCUUAGGCUUGCCGUCACACAGGCCCUUCAUCGACAUCAGAACCCACGUGAGCUGGUGCAAGACUGCGCUAAAACCAGGCUACAAAUUCGCGAUGUCGCGCCGACUGUCCUAACUGGUCAUCCCUGUUUUACACCAAUGUAUCGAAUACUACAGAAACUUUUGUUCGAUCCAGGAAUAAGAAAGAAUAUUAAGCAACGCUAUCGUAGGUUAACGAGCGUUUGUACCAGUUCGCUCAGAACUGUGUAUAGGAACCCGUGCUUGGUAAUUGUAAGUUUGGUACAGAUGGAUGUUCUACACCAGCCGGCGGGGGCACCCAAUACAUUUGAGUUGCGACUCCGGUGCCUAGUCCUAACAAAAGGACAUGGCGAUAUAACCGGGAGGCGAGGUAUCCCCGGUACAAUCGUGCACAAAUUCUUUCACGGAUAUACGAAGCGCCCUUGGUAUCUAAAUAAGGAAGGGCUGUGUCCUUCACGAUCAGCAAGUACCGAACUGAAGUCCGCUCCGUGCGAUUGUCUUGCUGACCCCCUGUGUAGAGCUGGUAUUGGGAAAGAACAGUGGGCUGUCACGGCAUUCCCCAGUCGGCGGUACGUUACGCUGGAACUGAUGCAGAUGUACGUCCGCCUUGAUACUAGUAGCGUGACUGUGCUUGUUGGACUGCUCCCUGCACUCUUCCUGGGUGCCAGGGGGCCUGUUAUCUUGGCAGCCGUCCUUGUGGCCUCGUCCCAGGUUCGACGUCACGAGCGGAUGCCAUCGGAGUAUCCUGCGCAUAUCCUAGGUGACGCAGGUAUCCACGUGGUAUGGGCGUGUUUCGCUGAAUGGUUAGGCAUUUUACCAUGGAAAGUUGGUUGGUCUGAAGCAGUGCAGGCUCGCCCAAGCCUGAGCAUUCAUAAUGACAGGCCGCACCGGAGUAAAGGGAUUUCAGACAUCGGUCUGCUCCUCACCAGAUGGUUCACGUGCCCGCAUAACGUCCUGGUUCGGGUGCAAGCGGAAGGACUCCGGGAUCUAGUAGUGCACGUUAGCGGCGGGACCGACUGGUGCUCUCUCCACGUAUACACUGUGUCCCCCAAGGUAGACAGACUGAGAUUCGGCCCAAUGAGUUGCUGCAGUGACGUGAGCGAAGAGACCAUGGCGAAUUUCGUGAUUCAGGGCGAGUGGGAGCCGGCAGUGGAUCGUUGGUGGAAAUACCGGUCGUGCACACCACAAAUUUCAGGUCAGAGGUAUUCACGAAGUCUCGACCUUCCCGGAUUCUUUACUAGCACCAGUCCUGGUAAUCGUAGUCAUAGUAUCUUAAGGAUAGAAGAUUACCAUCCACAUUGGCUACGUGCCGCAGGUCUAACGUUCAAACAGUCCUUACCUGAGUGUCCUCGCGAAGCGGGAGGUGCAGUGGGCCACUGGAAAUCAUACGUCCCUAACACGUUCCCAAGAGUCAGACGGACCCUACUCGACUUUUCGCUGUCCCAUGGCGAAAAGGGCAAUAACCUGUUCGGGGCGGUUCCCUUAUUAGCAUCGAACAUAGCCACGGCACUAGGGCGCGUUCUUGGGCAACGUUUUAGCAGGUUGACGGAUUACUACCCCUUUAGCCGCAGGGAUGUCACGAGUUAUAUUUUUGUACCUAUAGCCAAUCGGUUGGGGGACACACGGUUCCUUGACGAUGGGAAGUCGCGCGGUGCAGCGAAUGAUUUGCUACUAAGCACCAAGUGGGCUCAAAGGCCAUCCCCUUCGAAUCGCCCUUAUCUGGGUUCGGAUAAUAGGAGACUUCUUCUUCAGGCAACCCGCUCUUGCAGUGCAAGCUUGAGGGAAACUUCGAUCAUUCACGUAGUUAGACAUUAUGGACCAGAGCGGACACUGUGGCAGUUCUCCACAAGUCACUGUGCCCUCCCUGAAUGUCGUACACGGCGCAAGCUGGGAAUGCUACACGAUCACACAUGUCUGUCGGUCGUCUACUGUUUAUCGUAUUCUGCAGCUCCCUUCAGAAUCCCCCGAAGCGUUCACCGACAAACUCUCGAUCGCCAGCGGAUCUAUGGUCAAAACAAGGUAAUGACUGCAAGACCGCGCAGACAUGCGGGGCAACGAAGGCUAUCUUAUCUUGCGAGCACCGACGAAGAGUACCCAAAGUGGUACCAGACCCUGGCACUGUACGACAGUUGCGUCGCAAGAGCUCGAUACAUAAAUGGUUACCGCAGAACCCUCGUCGAGCUUACACAUUGGAAACUCAAAGGAAGCGACAUAUCCCGAGUAUGUAGCCGGAGCCGAGGCGGGUUUUACUGUGGGGCGGUAAGAGCUAGAGAUGCAGGUCAUGACAGGCCCUCAUUGCUUCAUAGUUCUGGCCAAUCCUCAAGUCCUAAUCGCUCACAUUGGUCCCAGCUACCCGAUCAUAGGGAGGUCGUAGUGUGUGCUCGCUCCUAUCUGUUCGCUGCGCACAACCGUGAUGCUAAAAGAGAUAAGGAGACAUGUCAAAUUGAUACUGAUUUACCGGAGAGACAAAAGACCCUCAACUCGCGCAACACUGGGCAUCCUCUUGUGAAUCGGAUGACCCGGUCUGAACUUGCGUGCUCUGCAGGCUACGGUCUUCAGACGAAGCAGAUAUUGCGACCUUUCUCACCGCCCUGGCGCUCUAGACGGGCGUUCUGUAGAUUAAAGGCGAUGAUUUGUAAUCCCAGGAUACCUUCGGACUAUGGCCCGGCGUCUGCCCUAGCGAGCUUCGCAUGCCUGCGAGCUAAUCAGAUUACACGACUCCUCUUUCACUGGUGCUCUGCGUCGACAACCUCCCACCGAAGACUGGACUACUGCUAUCUGUAUGGAGUCAUCGCUGAGGUCCCUAGAUUAUCGCUCGCGCCCCCACUUUUGCAGCCCUCGUUGAACCAGGUUCCCGGGCGGUCAUGCCACCCCAUGGUUAGAGAUGGGGUACUGAGGUACCUGUCUCGGCUAAGUCUACCUAAGUGUUGGUACAGAUUACUUACAAUGAGAAUCGGCAAUGUGAAUCUCUUGAUCCCGGUGUUCGGGAGGCAGGCCUCGUCUCGGCCCAGUCCGGCUAUGGCAGCUAGGAACCCCAGCAUUCAUGCGACAUGGGCGGCUACCGCGAAGGUCCACUGUCCAGAAUCUUUAUUAUCACUGACAGUCGCGCAAGAUACUUCUCUAUUUUUUACGGCCACUCAGGUAGGCUCAUCUGUACUCUUGAUGAAAGCAAGACAGCUAGCCACAUUGAGUCGAAUAUUGUCUUGCCCUCCUCAGGUCCUAGGGUUUGUCGGUUAUACCUCCGGACAGGAGAAGAGCACACAUCACAUAGCGUCUAUACCGCCCUUUAGGCGAGAACCCCUAGCGUACUAUGCAAAGCUAUCGAAAAGGUUGAAAGUUCGAAUCCAGUCUCACCUUGCAUUAGGCGCCCCAAGGAUGGCCCACUAUCGUCGUGUCGAAAGACUUUACCGGCCGCUCCUACAAAGUUUCUCCAGGAUCGUAAUUCGUUGGACACCCCGCAACCCUCCUCGUCUUGUCUGGUCCUUAGAAUGCAGUACGAUGGCUGGACGUGAAGCUCACUUAAAGUGCGCGACAAUUUGCUUUCUCUACAUGCCCCGUCUCGGACAAACCAUGCCAAAUGUGACCAGACCAUGCGACACGGGCGAUAAAGGAUCCUUGUUAUGUAACGCGUUCGACGCCCUGUCAGUCUCUGUGUAUAUGGGCAUGCAUAAUGAGUUUCCCAGUCCAUACGUGGUUUAUGAUCGAGGGCAUCAGGGACGGUACCAGGCCCGCAACGAAGGAGAAGUUCGGCGAGCGUCAUUUAAUGACCCGUUCAAACAUUUGUUCCCGGAGUUGGGCUGUCUUCAUAAGCUGCAAGGAGCCCGGUGGCGGGAGGGGGAAAUGGUCACGGGGGGACCUGGGUUUACCUUGCUUCCAGAGAGGAAGGAUUCAAACGUGGUACUCGACGACCCCCUACAUAGGAAAGGCCACCCGUCGGGAUAUACUGUUAUACAUGUGGGCGCGAAUCGGUUGUGGGCGGGAUCUCCAGGAGAUGGACAGAGGCAAGCUAGCACGAAUAGAGCACGCAGUUACGUGACCUGUCUCUACAUGAAUUUUAGUGUAACGGCGCAUCCUUGGAAGGAAGCGAAGCUGAGUGUGUUUACCCGUGUUAAUUGCUGGCAUGAGCAUCUGUUAGGCGUUUGGCAGAGCAUAAGGCCUCGAUGCGGCACGGAGCAGACAAACCACAUAUUUUACCCACGUACCUAUGUCGGGCGCCUCCAGAGGCUAUACUGCGCCCGCGCGUUCUCUCCUGAUAUAAGGAGUUUAGGCCUCCUGUUUCAACGGGCUAUAGCGCUCAGGGUAGAUUCUUUGGCCAACUCCUAUGUCAUUCAACCUUUUUCCAAAGUCCUUAGAAUUGGCGCUAUGAGCGAGCGUUUAACGACACAUGUCAAAGGGUUUUGUCUCGCAAUGACACACGUGCUCCCCUUAGAACCUCACUGUUCCGUUUUUGUUGGAACUAGCACUAAGCAGGUAUUUCCAACCCUACUACUAUACUGGCGUGUGGGACUGAGGCCUCAGAGCCUCAGUCAUAUGCGAUAUCAUAUUUUGACACGCGCGUUUUAUGGACCCUCAAUCCCGACAGUGUUAGGACAUUCCCGCCGCCCUCAAAACAGAGAUGGUGAAUUGUCCCCAGCUGUUGUUUGUUUUCUGAUAGUGGCAAGGCGCUCCGACGAUGCACCACGGAGAACCCGCGUCAGGAAUACCCCUCAACCGAAGACCGUUCUCACAUUAACGAGACUGCUGUGCUGGGAAACCCCCUUAUGGCAAUGGAGAAUUCAAAAAGCCCCAACGAUCGACCGUCUAUACCUCAAGUCUGGGAGUCCGACCCUCGCGCUUCCCAUAAUGAAGAGAUCUAAGGUGCUUCGGCUUGGGAAAGUGAAUGCGGACCUACUGUAUAGUCCCGUUUGUAAGGUUAAGAUAAGAUUUCGUAGCACUAUCAACAUACAGGGAUUUACGUGUUCCCAGCGGGCGGCAAGGGGACUGCCUUCGUCGCAGUGCGCGCAUUCCGUACAACUUUGGAUAGCCGUUGAGCUAGGCAGGGACAUUCGCCAACAUCGGGACCGACUUGGUAGUACAUUUAGAGACGGCGUGCUCACAACUCGGCAGAAACAAUACGACCCCCGAGGAAGUUAUAUCGGGGUGCCUAGAUCCUCAAUUAGUGGAUCCCGUUUUAGAUACCCGCCCUUACCCGCAGACGAUUACCGCCCGGGUAGCGACCGGGCGCAGCGAGUUCCACAGGAUGCGUGCACUAGCCUUAUAGCAACGCUGAGAGGACUGCGUUGGGUCGAGAUUACUCUACUGUCAAAACUGAUUCUAGUACAGUUAUGCACAGAUCUGCUACACAUUGAGGCGGGUGCAAACAAUGGAUGUUGCCCAGGCGAUUCCCGGCAGGAGAAUUGCCGAGCGCCAGAUAGGCAAGGACGUGCCUGUGAAUCAUGGGCAAGCCGUAAAUUCACAACAUCGAUAACAAGACUGAUCGACUCGCGUGGCCCUUCUCUAACCCUCCCGUGGACAUUAACUACGGGUAUAAAACGGAAGGAGACCAUAUUAGCGGGGGAACCUCUGUCCAUUGUUCGCCAAAGCCCAACCGGGCAGUAUACUGUCAUCUAUAUCCAAUGUUCCAUAAGUCAGUCAGAGACCGGCUUCCAUUCAGUGCAUGUGAUCACGCGUUCCCUCGAACACUUACCGUUGGUGCUUUGCUGCGAUGCUGCUAUGCAGCAACAGAAUCCACCGAUAUGGCUACUCGAACACCGCUAUGUCCCUAUGCAUAUAGAGCCUUUUCACGGAACACCUACCACAUGGGCACGAUUACAUAGAAGAUAUGUAAUCGUUCUAGAUGAGGAGGACGUAAAGACCCGCGCUCUGGGGCUACGGUGCGCUUCCCAAAAGCAGGUCGAGGAUUCUGGUACCCGCUAG")